2012 Genesis										6 May 2012
Lecture 2

GOD CREATED MAN

Genesis 1:26-2:3
Key verse 1:26 
"Then God said, "Let us make man in our image, in our likeness, and let them rule over the fish of the sea and the birds of the air, over the livestock, over all the earth, and over all the creatures that move along the ground."

Last week Paul spoke about the question of origins; the origins of creation and the origins of life. It is one of the most profound and important questions that we have to answer. Where do we come from? People want to know where they’re from because where we come from shapes who we are. That’s why when we meet someone, we always ask, “Where are you from?” It helps us understand who you are. When I tell people I am from Essex they say “Ah, that explains allot.” If we know where we are from we know where we are going and it helps to explain life in the middle.

The German theologian, Helmut Thielicke, pictured human history is a dramatic play, God is the playwright, and that there have been acts and scenes before us. We’re born. We come out onto the stage of history. Because we have no idea who the playwright is, we have no idea what the story is. We have no idea who the heroes and villains are. We have no idea when the story began or when it ends, what our role is or what lines we’re supposed to say. And so, we end up with a life of just great confusion. The book of Genesis tells us that we come from God. That God is the playwright, and that we’re going to God. And in the middle, we’re here to be in relationship with God and to work for the mission God gives to us. When we realise that we are created by God our life has meaning, value, purpose. We know where we come from, where we’re going, and what to do while we are here. Today we are going to learn that we are not only made by God but that we are made in the Image of God and find out what impact that has on our lives. 

I. GOD CREATED MAN IN HIS OWN IMAGE

Look at verse 26 - 27 Then God said, “Let us make man in our image, in our likeness, and let them rule over the fish of the sea and the birds of the air, over the livestock, over all the earth, and over all the creatures that move along the ground.”  So God created man in his own image, in the image of God he created him; male and female he created them. 

Here, once again, God speaks his creation in to being. Our God is a God who speaks, he spoke then and he continues to talk to us today, that is why we read the Bible and pray, Our God is a living God. The Bible tells us that the worship of many God’s is idolatry, and that there is only one God, yet here in Verse 26 we see God speaking about making man in “our image” God is talking of himself in the Plural, in Hebrew this is Elohim. Some commentaries say that God and the Angels were working together for creation. But this is not the case. If we look again at verse 27 we see that it says “So God created man in his own image, in the image of God he created him.”  This tells us that the creator is God not the angels; angels cannot create. This is the first time in the Bible that we hear about the Trinity, the Father, Son and Holy Spirit were working together to make you and I.

We have already seen the Holy Spirit in verse 2 hovering over the waters. Now we have this wonderful image of the Father, Son and Holy Spirit coming together to discus about their creation plan and coming to the conclusion “Let us make man in our image, in our likeness.” We are made in the image and likeness of God. What do these two words mean? An Image suggests something physical, visible, touchable, that does not mean that God is walking around constrained in a body as we are, but it suggests that our God is not an abstract idea he is a living God. And he made us as living beings. The word “Likeness” suggests personality or character. When we think of a particular person we do not so much see a physical image of them in our minds but we have sense of their character. When I think of Joshua I don’t think too much about his prominent jaw line, I think more about solid character, his dependability and a man of prayer. Many people say that my son Augustine and I are alike. Yet, visually his face has the image of Hannah, but we share the same likeness or character, he is a little odd and has a strange sense of humour, like myself. Both man and woman carry the image and the likeness of God. We are living beings who share the character and qualities of God. This is what makes us entirely different from anything else in God’s creation. Man is similar to the animals in some aspects, man is made from carbon just like the animals. Both man and the animals have the breath of life, they both eat, sleep and procreate. But unlike the animals we bear God’s image. Look at verse 27 again. The word created was repeated three times in this verse emphasising the fact that we are created separately from the animal, we are different, we are unique and set apart from the animals. 

In what ways do we bear the image and likeness of God? There are many characteristics that we share with God. God is creative and we are creative. I was amazed when I went to Joshua and Beth’s house last year, Beth’s paintings are amazing, one sees God’s creativity in her. God communicates and we also communicate, we also have language, we read and write. God is good, he is a God of justice, we have in us a desire for morality and justice, Paul works everyday with lawyers who are fighting for justice. God is emotional; he gets jealous, angry, happy and sad, just as we do. God is love and we also love. God is holy and we also have a desire for holiness. 

Look at verse 26 again. Because we bear the image of God we are able to rule over the fish of the sea and birds of air and over every living creature that moves along the ground. Some people say that we are equal to animals, that animals have the same rights and value as people, but this is not true, we are above the animals, we rule over them. Only man has the capacity to rule, rats don’t set up governments to control the mice. Dogs don’t establish councils to monitor the cats. Though man is made from carbon and breath just as the animals are he is made in the image of God, he is superior, he is the steward of all creation. 

Man falls into sin when he forgets his place, as people made in the image of God we are below God, we are not gods, but we are above the animals we rule over them. We sin because we think that we are either God – that we are in control, that we are the creators and rulers of our lives or when we think that we are animals and chase our base desires. We throw away the privilege that God has given to us and bring misery upon ourselves. We need to live as people, give control to our creator God but do not live like animals.  People who do not know Jesus Christ either live like little gods or like animals. They have lost the desire to know God. They throw away God’s image and instead live according to their physical base desires. When we look at our generation we can despair at the spiritual waste land that is out there. Yet we need to remember that in all people the image of God remains. In Genesis 9 after the fall and after the flood, God reiterated to Noah that God’s image remains in man (Ge 9:6) Though that image may be a dim light it is still there. This image of God in man is the basis of our evangelism. There is no one that we can speak to about the gospel who can say “I have no idea or concept about God.” There’s no such atheist. Every man and woman ever brought into this world has God’s image impressed on their hearts, they simply repress that reality. We should be encouraged when we go to do outreach that we do not have to build from nothing. God’s image is already there. When people are reunited with the creator God through Jesus and come to know and love him again, Gods image grows and comes alive.

II. GOD GAVE MAN A MISSION

Look at verse 28 God blessed them and said to them, “Be fruitful and increase in number; fill the earth and subdue it. Rule over the fish of the sea and the birds of the air and over every living creature that moves on the ground.” What was the fist thing that God did after the creation of man? He blessed him. This tells us about God’s priorities. Our God is good God who wants to bless his creation. Over 80 times in the book of Genesis he blesses. When we live with God our lives are blessed. We can sometimes say that life is tough, things are difficult. Just imagine how tough it would be without God’s blessing. James says that “Every good and perfect gift is from above” I think that we can all say this is true. When I look at my wife, my kids, this mission, my house, god’s perfect provision, even the blessing of Gods discipline, I can confidently say that My God is a God of blessing. We suffer when we go outside of God’s blessing and try to seek our pleasures elsewhere. We should always give thanks to our God and be satisfied with his abundant blessings on our lives. God said “Be fruitful and increase in number; fill the earth.” Have babies, raise children, children are a blessing from God. Sometimes we can complain that it is tough bringing up kids but kids are a gift from God, we need to nurture them and raise them but also enjoy them. We should enjoy the blessing of our kids, get to know them, spend time with them, and be their friend and shepherd. They are God’s blessing to us.

God said “fill the earth and subdue it. Rule over the fish of the sea and the birds of the air and over every living creature that moves on the ground” God gave man mission. Notice in verse 26 the close proximity of God’s decision for man’s creation and his plan to give man mission. Man was made to do a mission. Mission is another of God’s blessings to man. Our mission gives our lives meaning and purpose, through mission we grow in our relationship with God, without a mission our lives are hollow and empty, our relationship with God is weak. Mission keeps us young and vital. Most people, after retirement, stagnate. They sit in front of the TV, reminisce about the past and moan about “the state of young people these days.” Yet you look at Stanley, he is 82, he is young, energetic and making a difference to the lives of many young people. Dr John Jun said that the meaning of “retire” is that we simply change our tyres “re-tyre” and carry on. Let’s thank God that he has blessed us all with this lifelong mission to save the souls of young people. Let’s see our mission for what it really is – a blessing from God, and be faithful to the mission we have been given to the end. 

That Adam and Eve had to “subdue” tells us that all was not perfect in the beginning of creation. We have an image of life before the fall as being easy and trouble free, but this show us that there were unruly things in creation that needed subduing. As image bearers of God we should be those people who subdue. We should subdue our mission – conquer it, be victorious in it. Subdue our work – overcome the issues that our jobs throw at us. Subdue our families – love our spouse and raise our children well. Subdue our studies etc... If we do not subdue and rule over them they will subdue and rule over us. 

III. GOD SAID THAT IT WAS VERY GOOD

Look at verse 31 “God saw all that he had made, and it was very good. And there was evening, and there was morning—the sixth day.” At the end of each day, once he had finished the work of his creation God saw that it was good. However, when he had finished the work of creating men he said that it was “very good.” God was pleased with everything that he had created from the first day to the last, now that he had created man all his work of creation was complete, it was knitted together in perfect harmony. After the creation of man everything that God had created came to have meaning and value. Here we see how precious we are in the sight of God.

The fact that God said man is very good reveals to us that man is the object of God’s pleasure. It does not matter what we look like or what talents we may or may not have, simply because we carry his image, God is very pleased with us. This should be a great encouragement to us all. Many of us can be very down on ourselves. We are very quick to site our weaknesses. “I am not so clever, not so interesting, not very creative, not such a good communicator, I am weak, I am ugly, etc...” But God says you are very good! When someone gives us a compliment we instantly feel good about ourselves. But here in Genesis 1 this is not just anyone paying us a compliment, this is God almighty, this is the creator of the universe, he is telling you that you are very good. Why? Because you are made in the image of God. We become miserable when we compare ourselves to others, but this is totally fruitless. We are all unique, all different, all made in the image of God and he says to each one of us you are “very good.” Some do not like accepting compliments, actually, this is not a compliment it is a fact and we must accept this by faith. You are very good.

The fact that God was pleased with his creation also tells us that the purpose of one’s life is to please God his creator. Because man is created in God’s image we are most satisfied and happiest when we live to please our creator, when we give praise to him and glorify him. The reason for so much of man’s misery is because he lives to please himself without any regard for God. That person can never be truly satisfied. Paul said in 1 Corinthians 10:31 “So whether you eat or drink or whatever you do, do it all for the glory of God.” Whether it is study, work, mission, or pleasure with friends, if the purpose is to please God and reveal his glory then there is meaning, joy and satisfaction. May all that we do, what we say, how we live, our plans and hopes all be done to please God and reveal his glory.

IV. God rested on the Sabbath. 

Look at chap 2:1-3 “1 Thus the heavens and the earth were completed in all their vast array. By the seventh day God had finished the work he had been doing; so on the seventh day he rested from all his work. 3 And God blessed the seventh day and made it holy, because on it he rested from all the work of creating that he had done.”

God created the heavens and the earth and everything in it for 6 days and rested on the seventh day, blessed it and made it Holy. That he made it Holy means that he made a clear distinction between that day and all the rest. Therefore we to should keep the Sabbath holy. This is the 5th of the 10 commandments (Ex 28:8-11). How do we keep the Sabbath Holy? Firstly we should work hard for 6 days. Just as God created the whole universe for 6 days we also need to be faithful, work hard and get or jobs complete each day. Someone who is lazy for 6 days does not realize the purpose for the Sabbath or God’s love who gave us the day to rest from our labour. Second we do need to take a rest on the Sabbath, both us and our children need to take a break, stop working, enjoy God and enjoy each other. The Jews at that time would have allowed there servants and even their animals to rest on the Sabbath, this command is a command of God’s mercy and care for us. In Mk 2:27 Jesus said that the “Sabbath is made for man and not man for the Sabbath.” It is a gift of God for our blessing. God knows that man, made of the dust of the earth, needs to rest so he gave us the Sabbath. Third, on the Sabbath day one should worship the creator God with reverence and fear and keep our relationship with God fresh and alive. Also we should have spiritual fellowship with other believers, then there is true rest in God. True rest is not given when we physically do nothing, sitting in an armchair and drinking a beer. True rest comes when our soul is deeply satisfied, this can only come through the living and spiritual fellowship with God. Those who do not come to God can never find true rest. 

In summary, we are created by God. When we know where we come from we find out who we are - we are God’s most precious creation, created in God’s image and likeness, in his sight we are very good. Also when we know where we come from we know what we are supposed to be doing – we have a mission do to bring others back to their creator. We need to conquer and subdue this mission. Finally we find out where we are going. I have not spoken about this but one of the characteristics of God is that he is eternal, and as those made in God’s image we also have an eternal destiny, we are pressing on towards the kingdom of God. When we know where we come from we realise that our lives have meaning and value not just for this life but for the next. Let’s thank and praise or God who created us in his image and let’s conquer our mission and help other to find that image in them.


