2012 Genesis								3 June 2012
Lecture 6

GOD SAVES NOAH

Genesis 6:1 - 724
Key verse 6:18
“But I will establish my covenant with you, and you will enter the ark —you and your sons and your wife and your sons’ wives with you.”

The flood is a story of judgement and destruction but principally a story of salvation. Salvation based on God’s love for man is the key message of the whole bible and in today’s passage we see God making a covenant with Noah to save him and his family and from the flood. Because he trusted God Noah built the ark and he and his family were saved. Judgement is coming in our own generation and God has promised to save us in Jesus. We may fear preaching the covenant of judgement and salvation but I pray that like Noah we would trust God’s promise and boldly prepare for the coming judgement by preaching the covenant of salvation in this generation. 

First let’s consider the problem of sin in the time of Noah. Read verses 1 and 2; ‘When men began to increase in number on the earth and daughters were born to them, the sons of God saw that the daughters of men were beautiful, and they married any of them they chose.’ Later in the chapter we read that the earth was full of violence because of the corruption of man. This is a portrait of the problem of sin at the time of Noah and it focuses on marriage. Verse two tells us that men married in those times based on beauty and personal choice. But Genesis chapter 2 tells us that God created Eve as a suitable helper for Adam in his work as a steward of creation. Therefore not only were people choosing to marry for the wrong reasons but they had lost their sense of meaning and purpose in life. People at the time of Noah were living narrow, selfish, godless lives and their marriages were an illustration of this. 

Look at verse 3: ‘Then the Lord said, “My Spirit will not contend with man forever, for he is mortal; his days will be a hundred and twenty years.” The consequence of the way in which men were living was that God said his Spirit would not contend with man forever. The word contend means to hold with or to remain in. Chapter 2 tells us that man is made from dust but the thing which distinguishes us from the animals is that we have the Spirit of God in us. If you go to the park after the service and look at the ducks chasing each other around you will see how animals choose their mates. They look for the strongest and the most physically attractive mate. You don’t hear ducks discusses their personal interests, their faith or their life direction and praying for God’s wisdom before deciding to form a life long commitment to another duck. Ducks choose the best looking ducks to mate with and this is entirely natural. But men are not animals and when we behave like animals we live weak meaningless lives and consequently dishonour the Spirit of God in us. In the time of Noah this was so bad that God said his Spirit could no longer remain in men.

This was a time of spiritual corruption and God could no longer bear to see things continue as they were. Verse 5 tells us how God saw men’s hearts; ‘The Lord saw how great man’s wickedness on the earth had become, and that every inclination of the thoughts of his heart was only evil all the time.’ This is one of the most damning verses of the whole bible. Look again at the verse. God is talking about all humanity and he describes them as; wicked, in every thought, all the time. God is saying that every single person in Noah’s time was absolutely, fundamentally evil all of the time from the bottom of their hearts. This matters because the heart is where all our thoughts, emotions, ideas and actions begin. If men’s hearts were evil then so also would be their actions. 

Verse 6 tells us God’s reaction to this; ‘The Lord was grieved that he had made man on the earth, and his heart was filled with pain.’ God was grieved and he felt great pain. Grief and pain are emotions of love. God had made the world with love, he had made man, the pinnacle of his creation, in his own image with great love and now he was grieving because of man’s sin. This tells us that not only were people suffering from sin but God also suffered the pain of seeing their sin. In fact God did not just feel pain but a deep agony. In Isaiah God compares himself to a mother with her baby. A mother deeply loves her child and has great hopes and ambitions for it. Mothers want to see their sons grow as strong, wise and influential men and they are grieved when they fall into harm or waste their lives. God was deeply grieving because the men he had created were living corrupt and sinful lives. God really suffered because he deeply loved mankind. 

Verse 7 tells us about God’s reaction; ‘So the Lord said, ‘I will wipe mankind, whom I have created, from the face of the earth —men and animals, and creatures that move along the ground, and birds of the air—for I am grieved that I have made them.’’ God made a decision at this point that he would destroy all life on the earth. People say that this is unjust and that it is an overreaction or that this was God’s fault for making man in the first place. It is fashionable today to say that the God of the Old Testament is harsh and unforgiving but if we read verses 6 and 7 together we see that God’s decision to destroy the earth with a flood is a response to his pain and his grief. How can this be the case? The answer is that God does not want the suffering which comes from our sin to continue. Verse 11 says; ‘Now the earth was corrupt in God’s sight and was full of violence.’ Violence was the result of people’s sin. People suffered from violence, physically, emotionally and verbally from other people when they sinned against one another. They also suffered inner violence when they experienced self-condemnation or bitterness as a result of their own sin. Instead of allowing this to carry on indefinitely and watching man suffer God chose to judge because he loved mankind and wanted the suffering to end. His means of doing this was the flood. 

Look at verse 8; ‘But Noah found favour in the eyes of the Lord.’ There was one exception to the wickedness of mankind and that was Noah. Only Noah found favour in the eyes of the Lord. Verse 9 says; ‘Noah was a righteous man, blameless among the people of his time, and he walked with God.’ Noah’s life was in contrast to the rest of the world not because he was good but because he lived in the sight of God. As a son of Adam he was a sinner, an example of which we see after the flood. But verse 9 tells us that uniquely in the whole world Noah walked with God. Verse 13 tells us that this was a personal relationship because God spoke to Noah. So we can see that God loved Noah and Noah loved God. Consequently we see that Noah obeyed God. Verse 22 tells us that; ‘Noah did everything just as God commanded him,’ and chapter 7 verse 5; ‘Noah did all that the Lord commanded him.’ 

Between those two verses we see God’s instructions to Noah and these instructions make Noah’s obedience seem quite extraordinary. God instructed Noah to build an ark. Look at verses 14 – 16; ‘So make yourself an ark of cypress wood; make rooms in it and coat it with pitch inside and out. This is how you are to build it: The ark is to be 450 feet long, 75 feet wide and 45 feet high. Make a roof for it and finish the ark to within 18 inches of the top. Put a door in the side of the ark and make lower, middle and upper decks.’ God instructed Noah to build a boat. Noah’s obedience to this is extraordinary in two senses. First, because of the dimensions of the boat; it was about as high as this building and as long as the distance from here to Archway Bridge. This was an enormous boat and God was very precise in his instructions yet Noah obeyed and built the ark exactly as God had said. 

The second extraordinary thing about it was that Noah was not building it in the sea; in fact he was probably building an enormous boat in the middle of a desert. Noah obeyed God and he looked ridiculous as a result. My parents have a neighbour whose house looks as if no one lives there. He has windows broken by bombs which fell during world war two and the house is so untidy that when his cat died he did not find it for three days. The house looks derelict and local people think he is crazy. This is the kind of reputation Noah would have had, people thought he was crazy, he would have gained a reputation and become a tourist attraction, people would have gone out of their way to see the ‘incredible boat in the desert man’. No doubt they would have queued up to laugh at him and Noah would have had to endure a great deal of mocking. 

So why did Noah keep on building? The answer lies in God’s promise to Noah. Look at verses 17 and 18; ‘I am going to bring floodwaters on the earth to destroy all life under the heavens, every creature that has the breath of life in it. Everything on earth will perish. But I will establish my covenant with you, and you will enter the ark —you and your sons and your wife and your sons’ wives with you.’ 

God made a covenant with Noah. A covenant is a promise and God does not break his promises. God promised that he would save Noah when the flood came, look at God’s words to Noah; ‘you will enter the ark.’ Therefore Noah had no doubt that God would save him. It is an incredible grace that Almighty God, the creator of the universe, would make a covenant with a sinful man. God chose Noah and because Noah had a relationship with God he absolutely accepted God’s promise in the covenant. This also meant that Noah had holy fear because he knew who God is. But Noah also loved God because God had loved him. Therefore Noah was a man of faith, holy fear and a man who loved God. Consequently, he was willing to endure the humiliation of building the ark in the desert in order that God would be glorified and Noah and his family would be saved. 

Peter calls Noah ‘a preacher of righteousness’ (2 Peter 2:5). Genesis does not tell us that Noah preached to people but he certainly lived a life which set an example and challenged people. The ark was Noah’s witness. When people looked at what he was doing and asked questions he would have had the opportunity to tell them that he was walking with God, that God had spoken to him and that he was obeying God in preparation for the coming flood. Through his obedience Noah became a witness to the power and love of God and gave others the opportunity to repent and be saved. 

Chapter 7 completes the story. Verse 1 tells us that when the day came God told Noah to get into the ark; ‘The Lord then said to Noah, “Go into the ark, you and your whole family, because I have found you righteous in this generation.’ He instructed Noah to take ‘seven of every kind of clean animal’ and ‘two of every kind of unclean animal’. Then after seven days the rain came for forty days and forty nights and God sent his judgement in the flood, wiping from the face of the earth, every living creature he had made. 

The effect of the flood was devastating. Verse 21 tells us that; ‘Every living thing that moved on land perished—birds, livestock, wild animals, all the creatures that swarm over the earth, and all mankind.’ We cannot imagine the horror of the flood. From the ark Noah and his family could probably see the waters rising, animals running for high ground, people beginning to panic, houses and buildings flooding and being washed away and gradually everything around them disappearing until all they could see in every direction was water. The same water which had destroyed everything lifted the ark and the ark became the only place in the entire world with life in it. 

Chapter 7 does not concentrate on the horror of the flood but instead repeatedly talks about Noah, his family and the animals on the ark. Why is this? It is because the message of this passage is primarily about salvation. The story of Noah is the story of the bible, God is telling us through this passage that the world is facing judgement but that there is a covenant through which we can be saved. 

The story of Noah and the flood points to Jesus who is our ark and it teaches us about how we should live today. First of all we should be clear that the times of Noah are remarkably like our own. When we read in Genesis 6 of people marrying for beauty this sounds just like our own times. Jesus said; ‘As it was in the days of Noah, so it will be at the coming of the Son of Man. For in the days before the flood, people were eating and drinking, marrying and giving in marriage, up to the day Noah entered the ark; and they knew nothing about what would happen until the flood came and took them all away. That is how it will be at the coming of the Son of Man’. 

We are living in the end times. People are wicked, the thoughts of our hearts are evil all the time just like in Noah’s time. We can see murder, war, injustice, poverty and hatred all over the world. Just like Noah’s time judgement is coming upon this world. It may not be soon but it is coming for all people and the people around us are ignorant of what is to come. They are continuing to live sinful lives which cause violence both to them and to other people. 

As in Noah’s time marriage is in crisis. Half of marriages fail, many more people do not even bother to get married and young people are cynical about the purpose of marriage. The relationships which people enter into cause a great deal of suffering and violence. Over the past year I have been working with two 16 year olds who ended up having a baby together. Before the baby was born they had split up and so they tried to raise it together in their two homes until the baby was severely injured and social services took it away. Consequently there was a court case where the two families attacked each other and both were hurt. The baby ended up being given to the father and its mother can only see him once a week. Both children have left school and won’t go on to university and her whole family are moving away from the town to a completely new area. The great suffering and violence we see in relationships like this comes as the result of decisions made by people who are living for themselves. Just as in Noah’s time God is grieved and a time is coming when he will judge and end the suffering and violence caused by sin. 

As in Noah’s time all people are sinners and all stand condemned yet we also enjoy a covenant with God. Our covenant is in Jesus. John 3:16 says; ‘For God so loved the world that he sent his one and only Son, that whoever believes in him shall not perish but have eternal life.’ Jesus is the ark for those in this generation who simply believe in him. People like to argue that there are many ways to be saved. They say we have a Hindu ark, a Muslim ark, an ark of deeds and an ark of self-righteousness. But Jesus is very clear that there is only one way to be saved, he said; ‘Make every effort to enter through the narrow door, because many, I tell you, will try to enter and will not be able to.’ Of those left outside he said; ‘There will be weeping there, and gnashing of teeth…’ When the judgement comes we need to be in the covenant with Jesus or we will be condemned to an eternity in hell. There is no other way.

This leads us to the final question we need to ask ourselves based on this passage. Do we love God and our neighbours enough to live like Noah? We have an enormous responsibility to tell people about the coming judgement. This means building the ark in the view of other people and like Noah being preachers of righteousness in our generation. 
If we choose to live for Jesus, like Noah we risk being mocked. People ask why we give our time talking to students at UCL, why we spend our Sundays worshipping rather than taking part in the Queen’s Jubilee celebrations, why we invest so much time and energy into studying the bible and teaching it to other people. They tell us that there is no God and that we are following old fashioned superstitious beliefs. But like Noah we have found favour in the eyes of the Lord. God has called each of us and saved us through the blood of his son Jesus Christ because he loves us. The question is whether we love God and love other people enough to share the truth about the coming judgement. It is hard because people do not want to hear or believe this truth and we are fearful to tell them. Three weeks ago I approached a student at UCL. He seemed very confident and happy and said that he and his family had no interest in things like that. The first thought that entered my mind was to tell him that he was going to hell. This is true and he needed to hear both the truth of judgement and the love of God in salvation but I did not tell him either because I was afraid of what he would think. In an age of logic and rationalism we fear looking foolish because of our faith. 
But Noah challenges me in this. People today cannot see judgement coming any more than they could see the flood coming in the time of Noah. I am struck by the strength of Noah’s faith, love and holy fear which kept him going for so long and I ask myself why was Noah so sure that he was right to build the ark. The answer is in what God said to Noah, look again at verse 18; ‘I will establish my covenant with you, and you will enter the ark...’ God has promised to us that we will enter the ark of Jesus Christ. This means that we are already saved and that we have nothing to fear. Remember what we learned about Satan’s tricks in Genesis chapter 3. Satan wants us to believe that the promise is not absolute, that maybe we have misunderstood what God has told us like Eve did. So long as we retain this uncertainty in our hearts we will fear telling people about the covenant of judgement and salvation. This is why our relationship with Jesus is not just a one off salvation experience but a lifelong walk with Jesus in which we daily renew our relationship through his word, prayer and repentance. Like Noah we need to talk to God and listen to what he is saying to us and we need to accept that if we believe in Jesus, we have already been saved. If we live in this certainty then our lives and our words will be clear signs to other people that judgement is coming and that in Jesus they can be saved. 
In conclusion. God will judge the earth and all the people in it but he has made a covenant with us in his son Jesus Christ so that all who believe in him will be saved. We are living in the end times, people are facing judgement and it is our duty to warn them. Let’s hold on to the promise of our own salvation, walk with God and fearlessly preach the gospel so that others may be saved too. 
