2012 Genesis										27 May 2012
Lecture 5

SIN CROUCHING AT THE DOOR

Genesis 4:1-5:32 
Key verse 4:7 
“If you do what is right, will you not be accepted? But if you do not do what is right, sin is crouching at your door; it desires to have you, but you must master it.”

Last week we saw the account of the fall. As a result of sin God shut out Adam and Eve from the Garden of Eden and prevents their return with a flashing sword. It is no longer possible to go back and they must move on east of Eden. Today we are living east of Eden. We begin to see the devastating effects of sin on family and society. Yet although sin has entered the world God allows life to continue and faith continues outside the garden. Despite sin we see the incredible grace of God. Despite man’s sin God is gracious and provides hope that one day there will be one speaks a better word than the blood of Abel. 

Look at verse 1. “Adam lay with his wife Eve, and she became pregnant and gave birth to Cain. She said, “With the help of the LORD I have brought forth a man”. Here we have an obviously highly condensed account but the start is a verse of hope and of a mother’s joy. Eve is delighted and says, “With the help of the Lord I have brought forth a man.” Many of the commentators think Adam and Eve mistakenly thought Cain was the promised deliver of Genesis 3.15. The name Cain means "acquired” or “gotten”. It has the sense of meaning fruitful or successful. But with the birth of the second child an ominous element enters the story. The name Abel means "frail" and has the sense of meaning ‘worthless’ or ‘meaningless’. Can you imagine growing up being called ‘worthless’! As we know Hebrew names are much more than simply a title. The name suggests a very different attitude and vision of the parents towards the children. Notice in verse 2 that Eve does not praise God or make any comment on the birth of Abel. Cain was the strong successful one. Cain was the child of hope whereas Abel was the weaker, less successful one. There is a strong hint of favouritism and already at the birth of these two boys it seems that the seeds of arrogance and conceit have been planted in the heart of Cain. Yet the problem of sin is that it is subtle and hidden within. It’s the hidden early stages that must be dealt with. Anyone can recognise sin when it is murder but what of the early stages? I recently heard about the Mediterranean fruit fly and how it can devastate a crop. The reason is that the insect lays the egg in the blossom. The fruit grows around the egg and then sometime later the worm hatches inside the fruit and eats its way out. It utterly destroys a crop. Sin is like that. It begins in the human heart and, if unchecked, works its way out in thoughts, words, and deeds. 

So how does it work its way out here? Look at verses 3-5a: “In the course of time Cain brought some of the fruits of the soil as an offering to the Lord. But Abel brought fat portions from some of the firstborn of his flock. The Lord looked with favour on Able and his offering, but on Cain and his offering he did not look with favour.” Here we see two very similar accounts. Both have the same parents. Both men are working. Both come to God. Both make offerings to God. Both worship. Both believe in God and indeed we later see Cain talking and responding to God. The difference between these two men is very subtle. This is deliberate because the author is telling us that sin is subtle. The traditional idea is that good people are moral. Good people are hard working. Good people go to church and worship. In contrast bad people are feckless. Bad people are lazy. Bad people don’t believe in God. Yet we don’t see Cain drunkenly riding around on his camel shouting insults to God while Abel is a hardworking good man. Basically there is no difference between them. So what’s the problem? It’s subtle and it’s meant to be because it is a matter of the heart. 

As I said anybody can recognize sin when it shows itself in murder but what about the roots? What are the starting signs of sin revealed here in Cain? First, we get a hint of a difference in how Abel’s offering is described. In verse 4 we see Abel brought ‘fat portions’. He offered ‘some of the firstborn of his flock.’ To offer fat portions is to offer the best of the animal. To offer the firstborn is a risky thing to do and shows complete trust in God. It is easy making an offering when you know how many have been born and can work out after the event. If Abel was going to have 10 new sheep then offering the firstborn is perhaps easy. But what if only two sheep were born that year? Would you offer 50%? We tend to wait and see what we can offer yet the suggestion here is that Abel made an offering of the firstborn and trusted God to provide. In contrast Cain is simply described as offering ‘some of the fruit of the soil’.  The suggestion is of less heart and gratitude towards God. Abel’s heart was right before God whereas Cain’s was not. 

Second is the different offering itself. The reality is that we cannot tell from the text here what the difference between these men is. Yet looking back on this event the author of Hebrews sheds important light on what was happening in the hearts of each man when it says at chapter 11:4, “By faith Abel offered God a better sacrifice than Cain did. By faith he was commended as a righteous man, when God spoke well of his offering.”  The difference between the two is that Abel offered ‘by faith’. But what does it mean to offer by faith? We tend to think of faith as meaning ‘belief in God’ but clearly Cain believed in God. He was talking to God! He responded to God and clearly he believed in God and knew him! By faith means more than offering in faith in God in general. It is to offer in faith in the grace of God. It is faith in the work of God. Abel knew that God declared that the penalty for sin was death and seems to have sensed the need for a sacrifice which involved blood through the death of a substitute. As Hebrews tells us ‘without the shedding of blood there is no forgiveness” (Heb 9:22). Those animals offered by Abel pointed forward to the death of the Lamb of God, the Lord Jesus Christ, who would come to take away the sin of the world. Abel would not have known precisely how God was going to deal with sin but he did know that God would deal with sin and trusted in the work of God rather than his own work. 

In short we see there are basically only two types of offering to God. We either offer to God in response to salvation or we offer to God as a means of salvation to try and get something from God. Cain offered to God the work of his own hands in the expectation that he would get something from God and when he did not get what he wanted he was angry and downcast. In contrast Abel offered in faith trusting in the work that God had already done. He knew he needed a substitute and discerned how to approach the holy God. 

God didn’t accept Abel’s offering out of arbitrary unfairness. Nor did he accept it because it was Abel’s best effort. Abel was, by nature, just as much a sinner as Cain was. God accepted it because Abel offered it in faith in response to God’s word. It had nothing to do with Cain’s efforts or Abel’s efforts. It had everything to do with God’s just requirement for a blood sacrifice to be the only means of approaching Him.

Let me give you an example. Let’s say you really want to go to the Olympic 100 meter final and are an incredibly dedicated athletics fan. You arrive and try and walk in and are asked, “Where’s your ticket?” You say, “Oh, I don’t have one of those silly pieces of paper. But I want you to know that I am a committed athletics fan”. He will say, “I don’t care; you need a ticket to get into the final.” So you leave the stadium and go find an artist. You get him to draw a ticket with a great picture on it. You go back to the stadium and hand that ticket to the man. He looks at it and says, “What’s this?” You say, “That’s my ticket. You said I needed a ticket to get into the final.” You could argue with him all day that your ticket is prettier than those printed tickets everyone else is giving him. You’re probably right. But it won’t do you a bit of good. You can tell him how much effort and expense you went to in order to have that ticket made. He won’t care. The only way to gain entrance to the game is to present the ticket issued by the proper authority. It has nothing to do with your character. It has nothing to do with your dedication as a fan. It has nothing to do with the effort or expense you went to in order to produce your own version of it. It has everything to do with it being the ticket required by the management for entrance. 

God has said that the only ticket into heaven is perfect righteousness. No one has it. No one can achieve it. But in His grace, God offers it as a free gift through the death of His Son, the only acceptable substitute. Cain didn’t like that. His pride in his own efforts made him angry when his ticket was rejected. He was angry at God, but also at his brother, who got in by showing the right ticket. His anger led him into depression--his face was downcast (4:5). He grew jealous. If Cain had faith to seek for mercy, how would he have reacted? Cain could have looked back at what he had done and repented. He would have asked Abel and sought a better way. But Cain was the opposite. As verse 5 says he was very angry and his face was downcast. In this we see more of the heart of Cain and people like them. Cain’s tend to become upset and angry easily. Cain’s tend to anger and depression. Cain’s think they are right and God is wrong. Of course people do not say this outwardly but they become angry and depressed about their life. They become dark and gloomy as if somehow they have been cheated or deprived of the life that they want. ‘Why didn’t you bless me! Why didn’t you give me that job or that wife or that husband or that ministry or that blessing!” Whatever the hope when it is not given rather than repent and trust God’s work they get angry and depressed. 

So how did God deal with Cain? Does he immediately crush him for being such an ungrateful self righteous man? No. First we see God as wonderful counsellor. The God of the Old Testament is often said to be angry and tough. Yet does he say, ‘who do you think you are you ungrateful so and so? How dare you!” No. God is a wonderful counsellor. Look at verses 6-7: “Why are you angry? Why is your face downcast? If you do what is right, will you not be accepted? But if you do not do what is right, sin is crouching at your door; it desires to have you, but you must master it.” Rather than rebuke Cain God tries to help him with questions. Remember that God does not ask questions because he lacks information. Rather he is telling Cain that ‘your anger and foul mood should tell you something about yourself. The reason that you are angry and depressed is that you are not willing to submit to my way’.  God is gracious. Notice also that he comes to Cain before he has killed his brother. God does not wait but instead comes to him to try and help him. 

The second emphasis in coming to Cain is to help Cain understand how powerful and how serious sin is. We tend to think of a little anger or depression as ‘just my character. It’s just who I am’. But the language God uses is stark. Look again at verse 7c again –“sin is crouching at your door; it desires to have you, but you must master it”. This is the first mention of sin in the bible and perhaps the finest description. The metaphor of sin used here is of a predatory animal crouching coiled and ready to spring up. It tells us that sin is ready to pounce and has a deadly life of its own. An animal that is crouching does so in order to hide itself and look small. If you can see it you have a chance of avoiding it but if not then it’s more likely to get you. Likewise the better sin is at hiding in our lives the more likely it is to kill us. Through this metaphor God is telling us that sin is crouching. It looks so small. But the sins in our lives that seem so small, so unnoticed are the ones that will take you out. David knew and loved God – his lust seemed small but it took him out. What are your crouching sins? What are those small sins you tolerate? The little bit of laziness, of dodgy images, of anger, of pride. They seem small, almost unnoticed, but beware they can take you out. 

Third God warns that sin grows. Sin starts as a choice but becomes a power. As verse 7 says ‘it desires to have you’. In this God is telling us that sin is not neutral but rather will grow and take shape in our lives. Although sin starts as a choice it becomes an active power in our lives. We sin but that is not the end. Rather it becomes more powerful and easier the second time. You may decide not to forgive your parents some wrong or misdemeanor but very soon it will harden you and take over. You may decide just to look at one lustful image but very soon it grips and pollutes a whole life. If someone has a cancerous tumour you do not say, “Well I will wait a few years.” No! You do something about it and quickly. I remember a friend in Norway who was diagnosed with cancer and within a few days was on the operating table. Sin is far worse than a cancerous tumour. If the Holy Spirit convicts you or if someone else is kind enough to say “your sin is this or that” then like cancer we need to deal with it quickly. Jesus was very tough with sin – so much so he said we should cut off your right hand or pluck out an eye to deal with it (Mth 5:29-30). In short we must treat sin in our lives very very seriously. 

Cain was told what to do. He was told how serious it was. Yet rather than repent and think again about his offering he ignored it. Look at verse 8: ‘Now Cain said to his brother Abel, “Let’s go out to the field.”  And while they were in the field, Cain attacked his brother Abel and killed him.’ Cain did not accept God’s word. And just as God warned sin grew and became his master.  In his anger perhaps Cain thought ‘OK God if you want a blood sacrifice I’ll give you one!’ He murdered his brother in jealousy and rage.

Again did God strike him down with some lightening and kill him? No. Again God was graceful. Look at verse 9: “Where is your brother Abel?” “I don’t know. Am I my brother’s keeper?” God did not ask him because he did not know where Abel was. Rather God was offering Cain yet another chance to repent. Notice that within just one generation sin has spread within the family to murder. Where Eve had to be talked into her sin, Cain could not be talked out of it. Where Adam and Eve at least hid in shame on sinning, Cain is defiant and angry towards God. With the birth of Cain there was great hope and joy but soon it was clear that sin would not be answered by having a family. 

Again does God now strike Cain down? Perhaps a little fire and burning sulphur? No. Again God was graceful. Look at verses 10-12:“What have you done? Listen! Your brother’s blood cries out to me from the ground. Now you are under a curse and driven from the ground, which opened its mouth to receive your brother's blood from your hand. When you work the ground, it will no longer yield its crops for you. You will be a restless wanderer on the earth." 

‘Listen! Your brother’s blood cries out to me from the ground’. This is a powerful metaphor. We see here that innocent shed blood ‘cries out’ to God. It is telling us that injustice cries out to God and that God hears injustice. It means that God cannot ignore sin. It means that because of his justice it cries out to be dealt with. It wants to be rectified and put right. This means immediately we have a problem. People tend to read bible passages like this and think, ‘Well I’m more like Abel. I’m the good guy’. We easily read the gospels and think, ‘Oh those nasty Pharisees. OK I may not be perfect but I am better than them and if I try harder it will be OK’. But the truth is we have all sinned. We have all committed injustices that cry out to God for an answer. If we are coming to God hoping that our hearts are good enough or that our offerings are thankful enough we have a serious problem because our injustice cries out to God for an answer.

Is there hope? As can be seen throughout this passage God is graceful. Of course Abel’s sheep offering was never enough to forgive his sin but it pointed ahead to the one whose blood would answer this cry of God for justice. Jesus sprinkled blood speaks a better word than the blood of Abel (Heb 12:24). Jesus is our better Able. Jesus died for us in our place. Jesus blood cries out from the ground for us. And it cries out for justice not for mercy. Personally I have been gripped by this great truth for the last few weeks. This is because often when I pray I confess my sins and say ‘Lord please be merciful. Please be merciful.’ But then I sin again – usually in much the same way. Round and round it goes and it seems that I sin and confess the same sins year in year out. Fear, laziness, coldness, lust. I wonder will it be like this in 10 years or 20 or 30 years? I have an image of Jesus pleading, ‘Have mercy on Paul. Go on one more time.’ And the father saying ‘Mmm OK all right”. But when will God say “no more!” But this is not how Jesus blood cries out for us. He does not cry out for mercy but justice. It cries out to God that sin has been already paid for. Jesus blood cries out to the father “these people sinned and you demand death for sin. I have died for them’. Instead of God’s justice being our problem God’s justice now works for us. It means we can come to God is great confidence. Those in Jesus can never be condemned. It would be unjust to punish us twice. Jesus blood speaks a better word than the blood of Abel. 

There is a lot that I could say about the remaining verses and I commend them to you for personal study. For now a few points. First the mark of Cain. Cain grumbled to God that his punishment and thought it was too heavy. He whines and moans about his punishment yet still God is graceful Look at verse 15. “But the Lord said to him “Not so; if anyone kills Cain, he will suffer vengeance seven times over.”  Then The Lord put a mark on Cain so that no-one who found him would kill him.” Despite his lack of repentance God had mercy on Cain and protected his life. “If anyone kills Cain, he will suffer vengeance seven times over.” What does this mean? We do not know what the mark was but it shows God’s unchanging love. By giving a mark, God helped him to remember God who protected him. Cain sinned. But God loved him with unchanging love. God was waiting that he would repent and come back. God who gave Cain a mark is the God of mercy, kindness and patience (Ro2:4-5). 

Second sin grew. We see this in the appearance of Lamech. Look at verses 23-24 Lamech said to his wives, "Adah and Zillah, listen to me; wives of Lamech, hear my words. I have killed a man for wounding me, a young man for injuring me. If Cain is avenged seven times, then Lamech seventy-seven times." Lamech rejected the truth of marriage that man was to “be united to his wife” rather than “wives”. He took two wives and we see that families were increasingly fractured and the misery of polygamy began. We tend to look at Lamech and think ‘Yuk, how nasty!’ And indeed he is. But at least he married the two women. Many today do not even have the decency to marry. Many today have had far more than just two wives. Third in Chapter 5 sets out Adam’s genealogy. It spans 1,656 years of a family genealogy and is the longest period set out in the bible. Yet what does it show? Birth and death. Despite the 1656 years we see no progress in man. There is no moral evolution and growth in man. In all this time there is no answer to sin. People say could God not be patient? Well he gave over 1600 years and we see no progress. Save for one mysterious reference in Ch 5:24 “Enoch walked with God; then he was no more, because God took him away”. Very occasionally there was one who walked with God. Just once in 1656 years someone walked with God and went to heaven. If we put our hope in time or man making progress Chapter 5 tells us we have no hope. We need one who speaks a better word than the blood of Abel. 

In conclusion sin is subtle, powerful and desires to have us. Sin cannot be ignored and it cries out to God for justice. God cannot overlook it and will demand justice from the sinner or from Jesus. May God help us to accept the better word than the blood of Abel spoken by Jesus Christ!

