2012 Genesis 								     20 May 2012
Lecture 4

WHERE ARE YOU?


Genesis 3:1-24 
Key verse 3:9 
“But the Lord God called to the man, ‘Where are you?’

In last week's passage, we learned how much God loves man and wants the very best for him. We saw his desire to bless him in every part of his life, giving him the most beautiful environment, giving him work and mission, and blessing him with marriage. It was paradise. In this chapter we see man lose God’s blessing. 

It is the most tragic moment in human history, man is tempted to disobey God and his relationship with God was broken. But the question is how did it happen, what went wrong? This chapter answers that question very simply. The reason is the woman listened to a lie. This lie caused them to doubt God's love, and what follows is the devastation of sin that still lies at the heart of all human misery today. 

And yet despite the sin, despite the rebellion, the broken relationship, fear, shame and guilt what we see in this passage is God's unchanging love. We hear it in God’s call, "Where are you?" I pray that through this passage we may learn to see the lie of the serpent, that we may what sin is and where it may lie in our hearts, and most importantly, that we may hear God's amazing, unchanging love in his call, “Where are you?”

I.	Listening to the lie (3:1-6) 

Verse 1 says that among all creatures, serpent is most crafty. Crafty means clever but in a duplicitous dishonest way. We don’t know so much about the serpent, but it seems he already has the ear and trust of the woman, perhaps he is liked because of its cleverness. But here we see he is used as Satan’s instrument. Satan uses the craftiness of the serpent to tempt the woman. Look at verse 1b. He said to the woman, ‘Did God really say, “You must not eat from any tree in the garden”?’ This is quite a tricky question. Here, the serpent refers God as Elohim – emphasizing God’s authority but ignoring his love and grace. Also he uses the word “really”. This word makes us to doubt. For instance, even if we are sure of our salvation, if someone asks – are you really saved? Then, we can easily fall into doubt. 

The tone or atmosphere created by the serpent makes the woman doubt whether she can trust God’s word. It’s worth noting that Satan at this point does not make a direct attack on God, he simply sneers, making the woman feel stupid if she believes God’s word. “Did God really say?”….. “Did God really say that? And you believed him!” We can recognize the tone. The intellectual climate at universities these days can be hostile to God, and faith in God and trusting in his word is often considered anti-intellectual and unreasonable, naïve and stupid. But more often than not, students are not argued out of faith but simply influenced by an atmosphere of sneers and cynicism and mockery. It is the sneer of the serpent, which is not based on truth or cogent argument but simply influences through peer pressure.  

The serpent also asked whether God said – “You must not eat from any tree in the garden.” This is a total misquote of what God said. God said in 2:17, “You are free to eat from any tree in the garden but you must not eat from the tree of the knowledge of good and evil, for when you eat of it you will surely die.” But, the serpent made it as if God had forbidden them to eat fruit from any tree in the garden. 

Look at verse 2,3. “The woman said to the serpent, ‘We may eat fruit from the trees in the garden, but God did say, “You must not eat fruit from the tree that is in the middle of the garden, and you must not touch it, or you will die.”’ In the woman’s response we can see two ways in which she is vulnerable to the serpent. First her attitude is unthankful God clearly said they are free to eat from any tree. Amazing generosity! But the woman said that they “may” eat from the trees in the garden. It’s as if she does not appreciate the abundance of God’s provision and the freedom he has given her. She has begun to take God’s blessing for granted. Secondly one sees her lack of knowledge and understanding of God’s word. God said clearly that they must not eat from ‘the tree of the knowledge of good and evil.’ However, the woman just referred to the tree as ‘the tree that is in the middle of the garden.’ She had lost, or perhaps was never taught by the man, the reason for not eating the tree, Her knowledge and understanding of God’s word was superficial and imprecise. 

The woman not only forgot the name of the tree, she also added an unnecessary restriction onto the command, “You must not touch it.” We can detect here the woman’s slight grumbling heart, that rather than being thankful to God she resented his restriction. Satan didn’t miss this opportunity and said “You will not surely die.” God said, “ You will surely die” yet, Satan said “ you will not surely die.” This is a direct contradiction of God’s word. What begins with a subtle, undermining question ends with a blatant lie. Satan now begins a brazen assault of the character and motive of God. Look at verse 5. “For God knows that when you eat of it your eyes will be opened, and you will be like God, knowing good and evil.” The Satan suggests the reason for God’s command was because he wanted to restrict them from being like God, hold them back, prevent them from enjoying their full potential, life to the full. This is Satan’s desire, to render God a mean spoil sport. Because if he can do that he can make us doubt that God really loves us, and wants what is best for us. 

How often have we held make from entrusting our life and heart to God because we fear that if we do, somehow we will be worse off? I can remember the struggle I had as a young artist resisting God’s call on my life out of fear that if I whole heartedly followed God, that I wouldn’t be as good an artist and my life would not be as blessed or as fulfilled as I hope. Deep down my image of God was of a spoil sport, of a mean God who wanted to hold me back. How is it that we can think that a God who gave man life, who gave him a garden with every tree, who gave him the role of mission, who blessed him with marriage, would want to spoil our lives and prevent us from living life to the full. Jesus himself declared in Jn 10:10, “I have come that they may have life and have it to the full.” 

God is not a spoil sport! But he does give us a command to help man remember he is God and to protect him from what is harmful to him. The appeal Satan makes to the woman is first to that of experience-- “If you eat of it your eyes will be opened.” How often the appeal is to experience life. Advertising appeals to our desire for experience all the time, that “fulfillment and happiness can only be achieved if you buy this and experience this.” Likewise relationships, “You won’t be happy unless you have this or that girlfriend and do this or that with them.” Satan’s appeal is to knowledge, to experience, to have ‘one’s eyes opened.’ Again one can see the use of peer pressure; that if one doesn’t eat of the fruit, you will be naïve, intellectually backward, and unsophisticated, that loss of innocence and cynicism are necessary to be insightful. Jesus himself exposes this lie. He was without sin but he wasn’t naïve or weak. To remain in obedience to God and his word is not naivety, it is to trust him and draw on his wisdom and insight.

Secondly, Satan’s appeal to the woman is to that of pride; that if she eats the fruit, if she disobeys God, she will be like God. The implication here is that if we are like God, if we take the place of God, and subvert creation order we will be happy. It is to forget that happiness comes from enjoying a loving, trusting relationship with God through obedience. It is to replace God with something else, to seek fulfillment in work, ambition, relationships, or even mission. To be like God is to take control of our lives, and decide our own priorities rather than trust God. As believers we might be nodding our heads. But how often do we allow anxiety and worry rob us of happiness? What is worry and anxiety other than taking the place of God? Of saying to God, I don’t trust you, I don’t think you have me in your hands, I don’t think you love me in such a way that it will work out alright. It is to doubt God’s love and to be like God. Satan’s desire is that we believe his lie and doubt God wants the best for us, to think he is a spoil sport and that happiness lies outside of his command. The root of sin therefore lies not in the action but in the way we think about God.          

Look at verse 6. “When the woman saw that the fruit of the tree was good for food and pleasing to the eye, and also desirable for gaining wisdom, she took some and ate it. She also gave some to her husband, who was with her, and he ate it.” Here we see that how the woman thinks leads to her fall. Adam should have intervened, but instead he also eats the fruit.   

II. Adam, where are you? (3:7-9) 

Look at verse 7. “Then the eyes of both of them were opened, and they realised that they were naked; so they sewed fig leaves together and made coverings for themselves.” In one respect Satan was right, their eyes were opened, yet rather than becoming like God, they realize they were naked. Before, they were naked and felt no shame, now they felt shame and guilt. Rather than running to God with their problem, they tried to deal with the problem themselves by covering up their nakedness.

Look at verse 8. “Then the man and his wife heard the sound of the Lord God as he was walking in the garden in the cool of the day, and they hid from the Lord God among the trees of the garden.” When they heard the voice of their Lord God, they hid. This means that their relationship with God had changed. When I come home at the end of the day my joy is to open the front door and there is Sarah running to me and embracing me. She loves me because I’m her daddy. That was the relationship God had with the man and the woman but now tragically and devastatingly it had changed. God was now someone they hid from. Before committing sin, the sound of God made them happy and they worshipped him. They were full of thanks and praise. Now, after committing the sin, they suffered from fear and sense of guilt. They lsot their peace and their love relationship was broken. How does a person we hide from God? Actually, it’s pretty difficult. Ps 139 says, “Where can I go from your Spirit? Where can I flee from your presence? If I go up to the heavens you are there; if I make my bed in the depths you are there.” (7,8) God is everywhere, he knows everything about us. In that sense we can’t hide from him. But we try, simply by denying he is there, by not recognizing his existence. The fruit of sin, is first shame and guilt, then fear and anxiety and finally hiding from him and ultimately denying his existence. Man was created to serve God in his image. When a man hides from God, he loses his whole life purpose and becomes a wanderer.  

How did God help him then? Look at verse 9. “But the Lord God called to the man, ‘Where are you?” Satan had tempted them to doubt God’s love. God demonstrated his love for the man by calling out to him. One can understand the pain of God here as a pain of a father who has lost his beloved child. I remember the panic when for a few moments I lost sight of Sarah. It was the worst thing imaginable. Sin does the same thing to our relationship with God. God grieves for his children who are lost. He doesn’t stop loving them, he calls out to them, he searches for them with the deep desire to be reunited. To serch for someone who is missing is expensive. I think of Madeline Mccann, who has been searched for with all the police resources. It helps us to think about the love of God and what his search for his children would ultimately cost. God knew physically where his children were, as he does every lost sinner. But it would cost him his only son to get them back. The call “Where are you?” continues to be cried out, in every generation to every hiding and lost child of God. God’s love for them did not change because of their sin. His love remains unchanging and unconditional.

“Where are you?” is a question that is relational. God did not ask the man “what have you done?” God wanted the man to think about where he was in relation to his father God. What changed is not God but Adam. Shame, sense of guilt, fear, meaninglessness, pride, doubt and unthankful heart came into his heart and so he hid from God. Like Adam, we can commit sins because of our weaknesses. Yet, we must not stay in self-condemnation. The way to deal with sin is not to cover it over, not to pretend nothing happened and not to hide from God. The way to deal with sin is to ask the question where am I? What is it that separates me from my father God, and quickly run to him in repentance. “Where are you?” – God is God of love and grace who looks for one lost sheep (Luke 15:2-7). When a sinner returns, he is most happy and embraces him as he is. May God always help us to hear his call.

III. God promises Saviour (3:10-24) 

Look at verse 10. He answered, ‘I heard you in the garden, and I was afraid because I was naked; so I hid.’ Adam could not come to him because of shame. What did God say? Look at verse 11. And he said, ‘Who told you that you were naked? Have you eaten from the tree from which I commanded you not to eat?’ Rather than covering over the man’s sin, God questioned him. He wanted to help him look at what went wrong, and why he felt shame and fear, so that he could properly come to him in repentance. This is true love, not to ignore sin but to help a person truly repent and be forgiven.   

Look at verse 12. The man said, ‘The woman you put here with me – she gave me some fruit from the tree, and I ate it.’ Adam didn’t repent of his sin of disobedience clearly. Instead, he blamed his wife Eve and God for giving her to him. This shows that sin not only breaks his relationship with God but also his wife. The woman then blamed the serpent for sinning - The woman said, ‘The serpent deceived me, and I ate.’ (13) Verses 14-24 talks about how God cursed the serpent and punished Adam and Eve. However, at this very point, he also promised Saviour and loved them. 

First, God promised Saviour (14,15) 

Look at verse 14. “So the Lord God said to the serpent, ‘Because you have done this, ‘Cursed are you above all livestock and all wild animals! You will crawl on your belly and you will eat dust all the days of your life. Serpent was crafty and clever. Yet, he was cursed to crawl on his belly all his life. Serpent was used as Satan’s instrument and as a result became the most miserable animal. Look at verse 15. “I will put enmity between you and the woman, and between your offspring and hers; he will crush your head, and you will strike his heel.” This is a judgement not only to the serpent but to Satan. God promised to send a Saviour through the woman’s offspring who would crush his head. A serpent is helpless when his head is crushed. The woman’s offspring would also suffer. Christ would pay the ultimate price on the cross. Yet, through this suffering, Jesus would destroy the power of Satan to hold people in slavery. This was the first time God promised the coming of messiah. Our faithful God fulfilled this promise by sending Jesus and demonstrated his love through the cross. The answer to doubting God’s love is to look at the cross of Jesus. 
 
Second, God made garments of skin (16-21) 

Look at verse 16. To the woman he said, ‘I will make your pains in childbearing very severe; with painful labour you will give birth to children. Your desire will be for your husband, and he will rule over you.’ The woman had two punishments. First, the pain of childbirth. Childbirth was God’s blessing to the woman (Gen 1:28). Yet, now he increased the pain of childbirth. Through this pain, God wanted the woman to repent her sins and bear the fruit of repentance. Second, he made the woman desire her husband and be ruled by him. From this time, the woman lost her privilege to help him as a suitable helper and lived under the rule of her husband. This was true in all cultures throughout the history. Yet, women can have privilege to be a suitable helper again for men in Jesus. 

Then, how did God punish Adam? What was Adam’s sin? Look at verse 17a. To Adam he said, ‘Because you listened to your wife and ate fruit from the tree about which I commanded you, “You must not eat from it,” Because of this sin, Adam could eat through his painful toil throughout his life in the field with thorns and thistles. All creatures sighed (Rom 8:20-22). Here the word painful toil is equivalent to pains in childbirth. From this time on, men were degraded from someone who live for God’s mission to someone who works to eat. Second, he was sentenced to death. All men will return to the ground. Our souls then will be judged before him. This is the second death (Rev 21:8). In this second death, we can’t quit the suffering through another death. We will suffer endlessly in eternal hell. Through one man Adam’s disobedience, death came into this world and ruled over all the human beings. (Rom 5:12,15,17). Adam named his wife Eve after God’s punishment. This means the mother of all the living. Adam accepted God’s promise and longed for salvation through the woman’s off spring. 

Look at verse 21. The Lord God made garments of skin for Adam and his wife and clothed them. Fig leaves are not perfect for Adam and Eve to cover themselves. So, God made garments by sacrificing an animal for Adam and Eve. This reminds us of simple gospel through that we can’t hide our sins through our righteousness. But only when we are clothed by Jesus’ sacrifice, we can become righteous. (Gal 3:27). 

Third, God prepared the eternal life. (23-24) 

What was the final punishment to men who ate the fruit from the tree of the knowledge of good and evil? Look at verse 22. And the Lord God said, ‘The man has now become like one of us, knowing good and evil. He must not be allowed to reach out his hand and take also from the tree of life and eat, and live for ever.’

In one sense, by eating the fruit, men became like God in knowing good and evil. So, he expelled them from the garden. What does this mean then? It means that the man decide what is good and evil. It is God alone who can tell what is good and evil. But, by eating the fruit, he didn’t want to hear what God tells good and evil, but wanted to make his own decision –like God. When he rules over the garden according to his will rather than God’s will, he will only destroy it. So, he lost his privilege to live in the garden. Also, God didn’t want him to eat the fruit from the tree of life because then like Satan, man also will end up as an enemy of God. Therefore, God made man to toil. He can receive eternal life only when he is forgiven through Jesus – the offspring of the woman. Until his sin problem is completely solved, he was abandoned to eat from the tree of life. Therefore, God expelled them from the garden and put a sword flashing back and forth to guard the tree. 

In conclusion, God hates and punishes sins yet he loves sinners. He is God of love and mercy. Therefore, when we sin, we shouldn’t hide out of despair. Instead, we need to hear God’s voice who is searching for us “ Adam – where are you?” and come to him by faith. When we do so, God will forgive all our sins and love us as we are. May God help us to hear his voice this time who looks for us.  
